language: php

compiler:
  - gcc
  - clang

os:
  - linux

matrix:
  include:
    - php: 7.0
      env: USE_VALGRIND=1
    - php: 7.1
      env: USE_VALGRIND=1
    - php: 7.2
      env: USE_VALGRIND=1
    - php: 7.3
    - php: 7.4
    - php: nightly

addons:
  apt:
    packages: valgrind

notifications:
  email: dev@service.viest.me

before_script:
  - php -m
  - git submodule update --init
  - sudo apt-get install zlib1g-dev -y
  - phpize && ./configure --enable-reader && make clean && make

branches:
  only:
    - master
    - dev

script:
    - ./travis/run-test.sh
    - make clean && phpize --clean
    - phpize && ./configure --enable-reader && make clean && make
    - if [ -n "$USE_VALGRIND" ]; then REPORT_EXIT_STATUS=1 php -n run-tests.php -m -n -d extension_dir=./modules/ -d extension=xlswriter.so -P --show-all --set-timeout 120; fi
