name: php-ext-xlswriter

on: [push, pull_request]

jobs:
  run:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['8.0']
        include:
          - operating-system: 'ubuntu-18.04'
            php-versions: '7.0'
          - operating-system: 'ubuntu-18.04'
            php-versions: '7.1'
          - operating-system: 'ubuntu-18.04'
            php-versions: '7.2'
          - operating-system: 'ubuntu-18.04'
            php-versions: '7.3'
          - operating-system: 'ubuntu-18.04'
            php-versions: '7.4'
    name: PHP ${{ matrix.php-versions }} Test on ${{ matrix.operating-system }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}

      - name: Setup Dependencies
        run: |
          sudo apt-get --fix-broken install
          sudo apt-get update
          sudo apt-get install zlib1g-dev valgrind -y

      - name: Setup Submodule
        run: git submodule update --init

      - name: Build Extension And Execute Tests
        run: |
          php -m
          phpize && ./configure --enable-reader
          make clean && make && make test

      - name: Build Extension And Execute Valgrind Tests
        if: contains('7.0,7.1,7.2', matrix.php-versions)
        run: |
          phpize && ./configure --enable-reader
          make clean && make && make test
          REPORT_EXIT_STATUS=1 php -n run-tests.php -m -n -d extension_dir=./modules/ -d extension=xlswriter.so -P --show-all --set-timeout 120